apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2gnn-app
  namespace: h2gnn
  labels:
    app: h2gnn
    component: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: h2gnn
      component: app
  template:
    metadata:
      labels:
        app: h2gnn
        component: app
    spec:
      containers:
      - name: h2gnn-app
        image: h2gnn:latest
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3001
          name: metrics
        - containerPort: 3002
          name: health
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: h2gnn-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: h2gnn-config
              key: PORT
        - name: H2GNN_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: h2gnn-config
              key: H2GNN_STORAGE_PATH
        - name: H2GNN_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: h2gnn-config
              key: H2GNN_LOG_LEVEL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: h2gnn-config
              key: REDIS_URL
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: h2gnn-config
              key: POSTGRES_URL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: h2gnn-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: h2gnn-secrets
              key: anthropic-api-key
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: h2gnn-secrets
              key: google-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: storage
          mountPath: /app/storage
        - name: logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: h2gnn-storage
      - name: logs
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
